[workspace]
members = [
    "contracts/*",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
overflow-checks = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
